#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''管理APP页面元素定位路径'''


class AppLocator:
    approve_text = '//uni-view[text()="同意"]'
    switch_ip_link = '//uni-navigator[text()="切换IP"]'
    input_ip = '//uni-input[contains(@class,"input_ip")]//input'
    input_ip_box = '//uni-input[contains(@class,"input_ip")]'
    input_port = '//uni-input[contains(@class,"input_port")]//input'
    input_port_box = '//uni-input[contains(@class,"input_port")]'
    switch_ip_btn = '//uni-view[contains(@class,"btn-row")]'
    username = '//div[text()="请输入登录账号"]/following-sibling::input'
    password = '//div[text()="请输入登录密码"]/following-sibling::input'
    login_btn = '//uni-button[contains(@class,"login_btn")]'
    approve_checkbox = '//uni-view[contains(text(),"已经同意")]/preceding-sibling::uni-view'
    todo_title = '//uni-view[contains(text(),"待办业务")]'
    switch_company_btn = '//div[contains(@class,"uni-page-head-hd")]'
    switch_target_company = '//uni-view[text()="{}"]'
    main_title_company = '//div[contains(@class,"uni-page-head__title")]'
    icon_box = '//uni-view[contains(@class,"app-list-content")]'
    more_icon = '//uni-view[contains(text(),"更多")]'
    module_name = '//uni-view[contains(text(),"{}")]'
    module_title = '//div[@class="uni-page-head-bd"]/div[contains(text(),"{}")]'
    # 回款管理
    head_btn_right2 = '//div[contains(@class, "uni-page-head-ft")]/div[2]/i'  # 头部右侧数第二个按钮(新增)
    head_btn_right1 = '//div[contains(@class,"uni-page-head-ft")]/div[1]/i'  # 头部右侧数第一个按钮
    choose_customer = '//uni-view[contains(text(),"客户名称")]/following-sibling::uni-view[1]'
    search_input = '//*[@id="serachDiv"]/uni-input//input'
    search_btn = '//*[@id="serachDiv"]/following-sibling::uni-view[1]'
    customer_item_title = '//uni-view[contains(@class,"item-title")]/uni-view[contains(text(),"{}")]'
    choose_pay_type = '//uni-view[contains(text(),"付款方式")]/following-sibling::uni-view[1]'
    picker_option = '//div[contains(@class,"uni-picker-view-content")]/div[contains(text(),"{}")]'
    picker_confirm_btn = '//div[contains(@class,"uni-picker uni-picker-toggle")]//div[contains(text(),"确定")]'
    pay_type_text = '//uni-view[contains(text(),"付款方式")]/following-sibling::uni-view[1]//span'
    choose_bank = '//uni-view[contains(text(),"收款银行")]/following-sibling::uni-view[1]'
    bank_text = '//uni-view[contains(text(),"收款银行")]/following-sibling::uni-view[1]//span'
    payer = '//uni-view[contains(text(),"付款人")]/following-sibling::uni-view[1]//input'
    pay_account = '//uni-view[contains(text(),"付款账号")]/following-sibling::uni-view[1]//input'
    choose_return_type = '//uni-view[contains(text(),"回款类型")]/following-sibling::uni-view[1]'
    return_type_text = '//uni-view[contains(text(),"回款类型")]/following-sibling::uni-view[1]//span'
    return_money = '//uni-view[contains(text(),"回款金额")]/following-sibling::uni-view[1]'
    choose_product_line = '//uni-view[contains(text(),"产品线")]/following-sibling::uni-view[1]'
    choose_product_name = '//uni-view[contains(text(),"产品名称")]/following-sibling::uni-view[1]'
    price_policy_span = '//uni-view[contains(text(),"价格政策")]/following-sibling::uni-view[1]//span'
    choose_credit = '//uni-view[contains(text(),"欠款核销")]/following-sibling::uni-view[1]/uni-view'
    view_activity = '//uni-view[text()="查看优惠活动"]'
    activity_name = '//uni-text/span[contains(text(),"{}")]'
    product_line_item = '//uni-view[contains(@class,"son_content")]//uni-view[text()="{}"]'
    product_line_text = '//uni-view[contains(text(),"产品线")]/following-sibling::uni-view[1]/uni-view'
    product_item_checkbox = '//uni-view[contains(@class,"son_content")]//span[text()="{}"]/../preceding-sibling::uni-view'
    product_confirm_btn = '//uni-button[contains(@class,"goodsCarButton")]'
    add_text = '//uni-view[text()="新增"]'
    money_item_tr = '//uni-view[contains(@class,"choose_product_title")]/following-sibling::uni-view/uni-view'
    credit_tab_notdue = '//uni-view[text()="未到期"]'
    credit_tab_overdue = '//uni-view[text()="到期"]'
    credit_card = '//span[contains(text(),"{}")]/ancestor::uni-view[contains(@class,"card-title")]/..'
    uni_button_confirm = '//uni-button[text()="确定"]'
    remark = '//textarea[contains(@class,"uni-textarea-textarea")]'
    refresh_span = '//span[text()="点击刷新"]'
    son_content = '//uni-view[@class="son_content"]'
    take_photo = '//uni-view[@class="take-photo"]'
    uploaded_photo = '//uni-view[contains(@class,"upload")]//uni-image'
    submit_btn = '//uni-button[@class="by_from_btn_commit"]'
    submit_confirm_btn = '//uni-modal//div[contains(text(),"确定")]'
    back_icon = '//div[@class="uni-page-head-btn"]'
    # start_time = '//uni-picker[@data-name="start_time"]'
    # end_time = '//uni-picker[@data-name="end_time"]'
    return_list_item = '//uni-view[contains(@class,"card-body")]//span[text()="{}"]/ancestor::uni-view[@class="card-circle"]'
    return_serial_number = '//uni-view[contains(@class,"card-body")]//span[text()="{}"]'
    applyer = '//div[text()="请输入申报人名称"]/following-sibling::input'
    menu_approve = '//div[@class="uni-actionsheet__menu"]/div[contains(text(),"通过")]'
    approve_msg = '//div[text()="请输入审核通过意见"]/following-sibling::textarea'
    pass_btn = '//uni-button[contains(text(),"通过")]'
